declare -a folders=("./2d_rendering/sprite_sheets_and_2d_animation"
"./2d_rendering/making_a_font_atlas_generator_tool"
"./2d_rendering/bitmap_fonts"
"./2d_rendering/2d_gui_panels"
"./animation/particles_systems"
"./animation/hardware_skinning_part_2_skeleton_hierarchies"
"./animation/hardware_skinning_part_1_bones"
"./animation/hardware_skinning_part_3_keyframe_animation"
"./new_shader_stages/tessellation_shaders"
"./new_shader_stages/geometry_shaders"
"./basics/hello_triangle"
"./basics/vertex_buffer_objects"
"./basics/extended_initialisation"
"./basics/opengl4_shaders"
"./lighting_and_texture_maps/phong_lighting"
"./lighting_and_texture_maps/texture_maps"
"./mesh_files/importing_a_mesh_file"
"./tips_and_tricks/screen_capture"
"./tips_and_tricks/gamma_correction"
"./tips_and_tricks/extension_checks_and_the_debug_callback"
"./tips_and_tricks/video_capture"
"./tips_and_tricks/debugging_shaders"
"./tips_and_tricks/uniform_buffer_objects_and_mapping_buffers"
"./transformation/ray_based_picking"
"./transformation/vectors_and_matrices"
"./transformation/quaternion_quick_start"
"./transformation/virtual_camera"
"./multipass_rendering/switching_framebuffer"
"./multipass_rendering/image_processing_with_a_kernel"
"./multipass_rendering/colourbased_picking"
"./multipass_rendering/deferred_shading"
"./multipass_rendering/texture_projection_shadows"
"./more_advanced_lighting_and_texture_effects/spotlights_and_directional_light"
"./more_advanced_lighting_and_texture_effects/fragment_rejection"
"./more_advanced_lighting_and_texture_effects/normal_mapping"
"./more_advanced_lighting_and_texture_effects/distance_fog"
"./more_advanced_lighting_and_texture_effects/using_textures_for_lighting_coefficients"
"./more_advanced_lighting_and_texture_effects/multi_texturing"
"./more_advanced_lighting_and_texture_effects/alpha_blending_for_transparency"
"./more_advanced_lighting_and_texture_effects/cube_maps_sky_oxes_and_environment_mapping")


for i in "${folders[@]}"
   do
       cp CMakeLists.txt "$i";
   done
